/**
 * 型 `.d.ts` 自動生成の bundler 非依存コア。
 *
 * lism.config.js の breakpoints / props / traits / isFullMode から module augmentation の `.d.ts` を
 * プロジェクト直下へ生成 / 更新 / 削除する IO 部分。Vite プラグイン（`vite-typegen.ts`）だけでなく、
 * Next.js / webpack アダプタや CLI からも同じ処理を呼べるよう、Vite に依存しない関数として分離する。
 *
 * 生成物は **コミット対象**（next-env.d.ts 方式）。dev / build 起動時に内容が変わった時だけ書き込み
 * （HMR ループ回避）、追加キーが無くなった場合は生成物を削除する。
 */
import fs from 'node:fs';
import path from 'node:path';

import { loadBuildConfigs } from './load-config';
import { generateLismEnvDts, GENERATED_MARKER } from './gen-types';

/** 生成する `.d.ts` のファイル名（vite-env.d.ts / next-env.d.ts に倣ったプロジェクト直下配置）。 */
export const TYPES_FILENAME = 'lism-env.d.ts';

export interface SyncTypesOptions {
  /** lism.config の明示パス。未指定時は projectRoot から探索する。 */
  configPath?: string;
  log?: (message: string) => void;
}

/**
 * `.d.ts` の内容（`generateLismEnvDts` の結果）を projectRoot へ反映する IO 部分。
 *
 * - `content` あり: 内容が変わった時だけ書き込む（HMR ループ・無駄な git 差分の回避）。
 * - `content` が null: 追加 breakpoints / props が無いので、既存の生成物があれば削除する。
 */
export function writeLismEnvDts(projectRoot: string, content: string | null, log?: (message: string) => void): void {
  const filePath = path.join(projectRoot, TYPES_FILENAME);

  if (content === null) {
    // 自動生成マーカーを含むファイルだけ削除する（手書きの同名ファイルを巻き込まない）。
    if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8').includes(GENERATED_MARKER)) {
      fs.rmSync(filePath);
      log?.(`🧹 [lism-css] removed ${TYPES_FILENAME} (no extra breakpoints / props)`);
    }
    return;
  }

  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (current !== null && !current.includes(GENERATED_MARKER)) {
    log?.(`⚠️ [lism-css] skipped ${TYPES_FILENAME} because it was not generated by lism-css`);
    return;
  }
  if (current === content) return;
  fs.writeFileSync(filePath, content, 'utf8');
  log?.(`📝 [lism-css] generated ${TYPES_FILENAME}`);
}

/**
 * projectRoot の lism.config を読み、breakpoints / props / traits から `.d.ts` を生成 / 更新 / 削除する。
 */
export async function syncLismEnvDts(projectRoot: string, opts: SyncTypesOptions = {}): Promise<void> {
  const { mainConfig, defaultPropKeys, defaultTraitKeys, isFullMode } = await loadBuildConfigs(projectRoot, {
    configPath: opts.configPath,
  });
  writeLismEnvDts(projectRoot, generateLismEnvDts(mainConfig, defaultPropKeys, defaultTraitKeys, isFullMode), opts.log);
}
