/**
 * `tokens.json`（lism.config 互換の tokens オブジェクト）の検証と、その反映経路。
 *
 * 反映は2経路必要なので、検証済み tokens から生成した lism.config モジュール1本を両方の入口にする。
 * 1. React ランタイム（props → `var()` 変換）… `lismConfigAlias({ configPath })` で `lism-css/config.js` を差し替え
 * 2. CSS 変数定義 … `loadBuildConfigs(dataDir, { configPath }).mainConfig` を `serializeTokens()` へ
 *
 * 契約違反は警告にせず必ずエラーにする（警告だと `check` 成功の意味が崩れるため）。
 */
import fs from 'node:fs';
import path from 'node:path';

import { loadBuildConfigs, serializeTokens } from '@lism-css/plugin/builder';
import getTokenVarName from 'lism-css/lib/getTokenVarName';

import { isPlainObject, MockupContractError, type MockupTokens, type TokenEntry, type TokenGroupEntry } from './types.js';

export const TOKENS_FILENAME = 'tokens.json';
/**
 * 生成する lism.config モジュールのファイル名。
 *
 * `.mjs` にしない。`loadBuildConfigs()` の jiti は ESM ファイルをネイティブ import で読むため、
 * 同じパスを書き換えても Node の ESM キャッシュが効いて `tokens.json` の変更を拾えなくなる。
 * `.js`（jiti の transform 経路 + `moduleCache: false`）なら毎回読み直される。
 */
export const GENERATED_CONFIG_FILENAME = 'lism.config.js';

/** 新しいキーの追加を許可するトークン種別。それ以外は既存キーの値上書きのみ。 */
const NEW_KEY_ALLOWED_TOKENS = new Set(['color']);

/**
 * `serializeTokens()` が CSS 変数として出力しない値か。
 *
 * 一覧に出すのは「生成 CSS が実際に定義しているトークン」だけなので、除外規則は
 * `serializeTokens()` と揃える必要がある。片方だけ変わるズレを見つけやすいよう、
 * 複製したルールはこの関数1つに閉じ込める。
 */
function isOmittedTokenValue(value: string | number | null | undefined): boolean {
  return value === '-' || value === '' || value == null;
}

/** default-config の1トークン種別が持つ既存キー一覧（配列カタログにも対応）。 */
function defaultTokenKeys(catalog: unknown): string[] {
  if (Array.isArray(catalog)) return catalog.map((key) => String(key));
  if (isPlainObject(catalog)) return Object.keys(catalog);
  return [];
}

/**
 * `tokens.json` の中身を検証する。
 *
 * @param raw          パース済みの `tokens.json`
 * @param defaultTokens `loadBuildConfigs()` の `defaultConfig.tokens`（既存キー判定の正）
 * @param file         エラー表示用の絶対パス
 */
export function validateTokens(raw: unknown, defaultTokens: Record<string, unknown>, file: string): MockupTokens {
  if (!isPlainObject(raw)) {
    throw new MockupContractError(`${TOKENS_FILENAME} must contain a JSON object of token groups (e.g. { "color": { "brand": "#333" } }).`, {
      file,
    });
  }

  // ユーザー入力のキーを持たせる器は必ず null プロトタイプにする。
  // 素の `{}` だと `__proto__` などの予約キーが own key として保持されず、検証結果と実データがずれる。
  const tokens = Object.create(null) as MockupTokens;
  for (const [group, values] of Object.entries(raw)) {
    // `in` は `constructor` / `toString` / `__proto__` まで既知グループ扱いにしてしまうため hasOwn で判定する。
    if (!Object.hasOwn(defaultTokens, group)) {
      throw new MockupContractError(
        `${TOKENS_FILENAME}: unknown token group "${group}". Available groups: ${Object.keys(defaultTokens).join(', ')}.`,
        {
          file,
        }
      );
    }
    if (!isPlainObject(values)) {
      throw new MockupContractError(`${TOKENS_FILENAME}: "${group}" must be an object of token key / value pairs.`, { file });
    }

    const knownKeys = defaultTokenKeys(defaultTokens[group]);
    const entry = Object.create(null) as Record<string, string | number>;
    for (const [key, value] of Object.entries(values)) {
      if (!knownKeys.includes(key) && !NEW_KEY_ALLOWED_TOKENS.has(group)) {
        throw new MockupContractError(
          `${TOKENS_FILENAME}: "${group}.${key}" is not an existing token. Only "color" accepts new keys; other groups can override existing values only (${group}: ${knownKeys.join(', ')}).`,
          { file }
        );
      }
      if (typeof value !== 'string' && typeof value !== 'number') {
        throw new MockupContractError(`${TOKENS_FILENAME}: "${group}.${key}" must be a string or a number.`, { file });
      }
      entry[key] = value;
    }
    tokens[group] = entry;
  }

  return tokens;
}

/** `tokens.json` を読み込む。ファイルが無い場合は null（空トークン扱い）。 */
export function readTokensFile(dataDir: string): { raw: unknown; file: string } | null {
  const file = path.join(dataDir, TOKENS_FILENAME);
  if (!fs.existsSync(file)) return null;

  try {
    return { raw: JSON.parse(fs.readFileSync(file, 'utf-8')), file };
  } catch (error) {
    throw new MockupContractError(`${TOKENS_FILENAME} is not valid JSON: ${(error as Error).message}`, { file });
  }
}

/** `tokens.json` を読み、default-config を正として検証した結果を返す。 */
export async function loadTokens(dataDir: string): Promise<MockupTokens> {
  const found = readTokensFile(dataDir);
  if (!found) return {};

  const { defaultConfig } = await loadBuildConfigs(dataDir);
  return validateTokens(found.raw, defaultConfig.tokens, found.file);
}

/** 検証済み tokens から lism.config モジュールを生成し、そのパスを返す。 */
export function writeConfigModule(dir: string, tokens: MockupTokens): string {
  const file = path.join(dir, GENERATED_CONFIG_FILENAME);
  const body = `// Generated by @lism-css/mockup from ${TOKENS_FILENAME}. Do not edit.\nexport default ${JSON.stringify({ tokens }, null, 2)};\n`;
  fs.writeFileSync(file, body, 'utf-8');
  return file;
}

/**
 * マージ済みトークンを、ビューアのトークン一覧が読める形へ整理する。
 *
 * 出すのは生成 CSS が実際に定義しているトークンだけ（`isOmittedTokenValue()` を参照）。
 *
 * @param mergedTokens  `mainConfig.tokens`（`tokens.json` 反映後のマージ結果）
 * @param defaultTokens `defaultConfig.tokens`（既存キー判定の正）
 * @param overrides     検証済み `tokens.json`（`source` 判定に使う）
 */
export function collectTokenGroups(
  mergedTokens: Record<string, unknown>,
  defaultTokens: Record<string, unknown>,
  overrides: MockupTokens
): TokenGroupEntry[] {
  const groups: TokenGroupEntry[] = [];

  for (const [group, valueMap] of Object.entries(mergedTokens)) {
    // 配列カタログ（キーだけの登録）などは CSS 変数を持たないため、serializeTokens と同じ規則で飛ばす。
    if (!isPlainObject(valueMap)) continue;

    // 上書き元は null プロトタイプのユーザー入力なので、`in` ではなく hasOwn で own key だけを見る。
    const overrideGroup = Object.hasOwn(overrides, group) && isPlainObject(overrides[group]) ? overrides[group] : null;
    // 既存キー一覧は上書きがある種別でだけ必要（default しか無いなら判定に使わない）。
    const knownKeys = overrideGroup ? defaultTokenKeys(defaultTokens[group]) : [];

    const tokens: TokenEntry[] = [];
    // 値は string | number 前提（default-config の定義と `validateTokens` の契約）。serializeTokens と同じ見なし方。
    for (const [key, value] of Object.entries(valueMap as Record<string, string | number>)) {
      if (isOmittedTokenValue(value)) continue;

      const isOverride = overrideGroup !== null && Object.hasOwn(overrideGroup, key);
      const source: TokenEntry['source'] = isOverride ? (knownKeys.includes(key) ? 'overridden' : 'custom') : 'default';

      tokens.push({ key, varName: getTokenVarName(group, key), value: String(value), source });
    }

    if (tokens.length > 0) groups.push({ group, tokens });
  }

  return groups;
}

/**
 * 生成 config を反映した CSS 変数定義と、その内訳（ビューアのトークン一覧用）を作る。
 *
 * ビューアは Lism 標準の `lism-css/main.css` を読むため、main 側の BuildConfig を直列化する。
 * React ランタイム（`lism.config.js` は `isFullMode` を持たない）も main 側の prop 設定で動くので、
 * CSS・コンポーネント・トークン一覧の3つがすべて同じモードで揃う。
 * CSS と一覧は必ず同じ config から作る（`loadBuildConfigs()` は1回だけ呼び、両者のずれを防ぐ）。
 */
export async function buildTokensArtifacts(
  dataDir: string,
  configPath: string,
  overrides: MockupTokens
): Promise<{ css: string; groups: TokenGroupEntry[] }> {
  const { mainConfig, defaultConfig } = await loadBuildConfigs(dataDir, { configPath });
  return {
    css: serializeTokens(mainConfig),
    groups: collectTokenGroups(mainConfig.tokens, defaultConfig.tokens, overrides),
  };
}
