/**
 * `tokens.json`（lism.config 互換の tokens オブジェクト）の検証と、その反映経路。
 *
 * 反映は2経路必要なので、検証済み tokens から生成した lism.config モジュール1本を両方の入口にする。
 * 1. React ランタイム（props → `var()` 変換）… `lismConfigAlias({ configPath })` で `lism-css/config.js` を差し替え
 * 2. CSS 変数定義 … `loadBuildConfigs(dataDir, { configPath }).fullConfig` を `serializeTokens()` へ
 *
 * 契約違反は警告にせず必ずエラーにする（警告だと `check` 成功の意味が崩れるため）。
 */
import fs from 'node:fs';
import path from 'node:path';

import { loadBuildConfigs, serializeTokens } from '@lism-css/plugin/builder';

import { MockupContractError, type MockupTokens } from './types.js';

export const TOKENS_FILENAME = 'tokens.json';
/**
 * 生成する lism.config モジュールのファイル名。
 *
 * `.mjs` にしない。`loadBuildConfigs()` の jiti は ESM ファイルをネイティブ import で読むため、
 * 同じパスを書き換えても Node の ESM キャッシュが効いて `tokens.json` の変更を拾えなくなる。
 * `.js`（jiti の transform 経路 + `moduleCache: false`）なら毎回読み直される。
 */
export const GENERATED_CONFIG_FILENAME = 'lism.config.js';

/** 新しいキーの追加を許可するトークン種別。それ以外は既存キーの値上書きのみ。 */
const NEW_KEY_ALLOWED_TOKENS = new Set(['color']);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** default-config の1トークン種別が持つ既存キー一覧（配列カタログにも対応）。 */
function defaultTokenKeys(catalog: unknown): string[] {
  if (Array.isArray(catalog)) return catalog.map((key) => String(key));
  if (isPlainObject(catalog)) return Object.keys(catalog);
  return [];
}

/**
 * `tokens.json` の中身を検証する。
 *
 * @param raw          パース済みの `tokens.json`
 * @param defaultTokens `loadBuildConfigs()` の `defaultConfig.tokens`（既存キー判定の正）
 * @param file         エラー表示用の絶対パス
 */
export function validateTokens(raw: unknown, defaultTokens: Record<string, unknown>, file: string): MockupTokens {
  if (!isPlainObject(raw)) {
    throw new MockupContractError(`${TOKENS_FILENAME} must contain a JSON object of token groups (e.g. { "color": { "brand": "#333" } }).`, {
      file,
    });
  }

  // ユーザー入力のキーを持たせる器は必ず null プロトタイプにする。
  // 素の `{}` だと `__proto__` などの予約キーが own key として保持されず、検証結果と実データがずれる。
  const tokens = Object.create(null) as MockupTokens;
  for (const [group, values] of Object.entries(raw)) {
    // `in` は `constructor` / `toString` / `__proto__` まで既知グループ扱いにしてしまうため hasOwn で判定する。
    if (!Object.hasOwn(defaultTokens, group)) {
      throw new MockupContractError(
        `${TOKENS_FILENAME}: unknown token group "${group}". Available groups: ${Object.keys(defaultTokens).join(', ')}.`,
        {
          file,
        }
      );
    }
    if (!isPlainObject(values)) {
      throw new MockupContractError(`${TOKENS_FILENAME}: "${group}" must be an object of token key / value pairs.`, { file });
    }

    const knownKeys = defaultTokenKeys(defaultTokens[group]);
    const entry = Object.create(null) as Record<string, string | number>;
    for (const [key, value] of Object.entries(values)) {
      if (!knownKeys.includes(key) && !NEW_KEY_ALLOWED_TOKENS.has(group)) {
        throw new MockupContractError(
          `${TOKENS_FILENAME}: "${group}.${key}" is not an existing token. Only "color" accepts new keys; other groups can override existing values only (${group}: ${knownKeys.join(', ')}).`,
          { file }
        );
      }
      if (typeof value !== 'string' && typeof value !== 'number') {
        throw new MockupContractError(`${TOKENS_FILENAME}: "${group}.${key}" must be a string or a number.`, { file });
      }
      entry[key] = value;
    }
    tokens[group] = entry;
  }

  return tokens;
}

/** `tokens.json` を読み込む。ファイルが無い場合は null（空トークン扱い）。 */
export function readTokensFile(dataDir: string): { raw: unknown; file: string } | null {
  const file = path.join(dataDir, TOKENS_FILENAME);
  if (!fs.existsSync(file)) return null;

  try {
    return { raw: JSON.parse(fs.readFileSync(file, 'utf-8')), file };
  } catch (error) {
    throw new MockupContractError(`${TOKENS_FILENAME} is not valid JSON: ${(error as Error).message}`, { file });
  }
}

/** `tokens.json` を読み、default-config を正として検証した結果を返す。 */
export async function loadTokens(dataDir: string): Promise<MockupTokens> {
  const found = readTokensFile(dataDir);
  if (!found) return {};

  const { defaultConfig } = await loadBuildConfigs(dataDir);
  return validateTokens(found.raw, defaultConfig.tokens, found.file);
}

/** 検証済み tokens から lism.config モジュールを生成し、そのパスを返す。 */
export function writeConfigModule(dir: string, tokens: MockupTokens): string {
  const file = path.join(dir, GENERATED_CONFIG_FILENAME);
  const body = `// Generated by @lism-css/mockup from ${TOKENS_FILENAME}. Do not edit.\nexport default ${JSON.stringify({ tokens }, null, 2)};\n`;
  fs.writeFileSync(file, body, 'utf-8');
  return file;
}

/**
 * 生成 config を反映した CSS 変数定義を作る。
 *
 * ビューアは `lism-css/full.css` を読むため、full 側の BuildConfig を直列化する。
 */
export async function buildTokensCss(dataDir: string, configPath: string): Promise<string> {
  const { fullConfig } = await loadBuildConfigs(dataDir, { configPath });
  return serializeTokens(fullConfig);
}
