/**
 * ビューアとデータディレクトリをつなぐ仮想モジュール。
 *
 * `import.meta.glob` は「glob 引数がリテラル必須・vite root 基準」のため、固定ビューアの静的コードから
 * 実行時指定の外部ディレクトリを列挙できない。そこで CLI 側で列挙結果をモジュールとして供給する。
 *
 * - `virtual:lism-mock/pages` … 画面一覧（表示順ソート済み）＋各ページの動的 import
 * - `virtual:lism-mock/tokens.css` … `serializeTokens()` の結果 CSS
 *
 * ビューアはこの2つ以外にデータディレクトリの情報を直接参照しない。
 */
import type { Plugin } from 'vite';

import { toImportSpecifier } from '../core/paths.js';
import type { MockRuntime } from '../core/runtime.js';
import type { MockData } from '../core/types.js';

export const VIRTUAL_PAGES_ID = 'virtual:lism-mock/pages';
export const VIRTUAL_TOKENS_CSS_ID = 'virtual:lism-mock/tokens.css';
/** `check` の bundle 検証用 entry（全ページを静的 import する。ビューアは使わない）。 */
export const VIRTUAL_CHECK_ENTRY_ID = 'virtual:lism-mock/check-entry';

/** rollup 慣習の `\0` 付き解決済み id（他プラグインが触らないようにするため）。 */
export const RESOLVED_VIRTUAL_PAGES_ID = `\0${VIRTUAL_PAGES_ID}`;
export const RESOLVED_VIRTUAL_TOKENS_CSS_ID = `\0${VIRTUAL_TOKENS_CSS_ID}`;
export const RESOLVED_VIRTUAL_CHECK_ENTRY_ID = `\0${VIRTUAL_CHECK_ENTRY_ID}`;

/** ページを import する信頼済み仮想モジュール（解決前後どちらでも）か。 */
export function isPageImporterId(id: string): boolean {
  return id === VIRTUAL_PAGES_ID || id === RESOLVED_VIRTUAL_PAGES_ID || id === VIRTUAL_CHECK_ENTRY_ID || id === RESOLVED_VIRTUAL_CHECK_ENTRY_ID;
}

/** `virtual:lism-mock/pages` のモジュールコードを生成する。 */
export function generatePagesModule(data: MockData): string {
  const entries = data.pages.map((page) => {
    const lines = [`    id: ${JSON.stringify(page.id)}`, `    label: ${JSON.stringify(page.label)}`];
    if (page.category !== undefined) lines.push(`    category: ${JSON.stringify(page.category)}`);
    // ページ実体は絶対パスで import する（server.fs.allow にデータディレクトリを含めることで許可）。
    lines.push(`    load: () => import(${JSON.stringify(toImportSpecifier(page.file))})`);
    return `  {\n${lines.join(',\n')},\n  }`;
  });

  return [
    '// Generated by @lism-css/mock. Do not edit.',
    `export const title = ${JSON.stringify(data.config.title ?? null)} ?? undefined;`,
    `export const pages = [\n${entries.join(',\n')}${entries.length > 0 ? ',\n' : ''}];`,
    '',
  ].join('\n');
}

/**
 * `check` の entry。全ページを**静的 import** して副作用のある形で参照する。
 *
 * 動的 import だけの `virtual:lism-mock/pages` を entry にすると、vite の app ビルドは
 * entry の export を保持しない（`preserveEntrySignatures: false`）ため丸ごと tree-shaking され、
 * 「ページを1つも bundle していないのに成功する」検証になってしまう。
 */
export function generateCheckEntryModule(data: MockData): string {
  const imports = data.pages.map((page, index) => `import * as page_${index} from ${JSON.stringify(toImportSpecifier(page.file))};`);
  const refs = data.pages.map((_page, index) => `page_${index}`);

  return [
    '// Generated by @lism-css/mock. Do not edit.',
    `import ${JSON.stringify(VIRTUAL_TOKENS_CSS_ID)};`,
    ...imports,
    // globalThis への代入は副作用があるため tree-shaking されない。
    `globalThis.__LISM_MOCK_CHECK__ = [${refs.join(', ')}];`,
    '',
  ].join('\n');
}

/** 仮想モジュールを供給する vite プラグイン。 */
export function virtualModulesPlugin(runtime: MockRuntime): Plugin {
  return {
    name: 'lism-mock:virtual-modules',
    enforce: 'pre',

    resolveId(source) {
      if (source === VIRTUAL_PAGES_ID) return RESOLVED_VIRTUAL_PAGES_ID;
      if (source === VIRTUAL_TOKENS_CSS_ID) return RESOLVED_VIRTUAL_TOKENS_CSS_ID;
      if (source === VIRTUAL_CHECK_ENTRY_ID) return RESOLVED_VIRTUAL_CHECK_ENTRY_ID;
      return null;
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_PAGES_ID) return generatePagesModule(runtime.data);
      if (id === RESOLVED_VIRTUAL_TOKENS_CSS_ID) return runtime.tokensCss;
      if (id === RESOLVED_VIRTUAL_CHECK_ENTRY_ID) return generateCheckEntryModule(runtime.data);
      return null;
    },
  };
}
