var doc = openDocument(config.aiPath);
if (!doc.saved) throw new Error('Save the output document before exporting');
exportBoards(doc);
var folder = new Folder(config.exportDir);
if (folder.exists) throw new Error('Use a fresh export directory');
if (!folder.create()) throw new Error('Cannot create export directory: ' + folder.error);
var options = new ExportForScreensOptionsWebOptimizedSVG();
options.cssProperties = SVGCSSPropertyLocation.PRESENTATIONATTRIBUTES;
options.coordinatePrecision = 3;
options.svgId = SVGIdType.SVGIDMINIMAL;
options.svgMinify = false;
options.svgResponsive = false;
options.fontType = SVGFontType.OUTLINEFONT;
var selection = new ExportForScreensItemToExport();
selection.artboards = '1-' + doc.artboards.length;
selection.document = false;
doc.exportForScreens(folder, ExportForScreensType.SE_SVG, options, selection, '');
log.push('Exported ' + doc.artboards.length + ' SVGs');
